### ISSUE TITLE
USER STORY: Setup Django

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#11]
As a Developer, I want to set up Django and install the libraries that I need to get the environment setup properly

**Tasks**

- [x]  Install Django
- [x]  Install dj_database_url psycopg2
- [x]  Install dj3-cloudinary-storage
- [x]  Create a requirements.txt file
- [x]  Create the Django project – called veglife
- [x]  Create the first app – called 'posts' and add it to the installed apps in the settings.py

EPIC: #1

**Comment by Sean-OBrien95** [comment]
Blank
