### ISSUE TITLE
USER STORY: View own profile

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#14]
As a User, I would like to be able to view my own profile and also see what other users can see when they view my profile

**Acceptance Criteria**

-  Acceptance Criteria 1:

  Given that I am logged into my account
  When I can access an option to view my profile
  Then my profile details appear as they would appear to other people

-  Acceptance Criteria 2:

  Given that I have a user profile,
  When I click on my user name on my user card
  Then I can bring up my full user profile as it appears to other users

**Tasks**

- [x] Develop a link for users to view their own profile when logged in
- [x] Develop a user card that summarises a users details
- [x] When users click on the user card, they are redirected to the full user profile.

EPIC: #2

**Comment by Sean-OBrien95** [comment]
Blank

**Comment by Sean-OBrien95** [comment]
Have made user profile cards obselete, only link to full profile on final build
