### ISSUE TITLE
USER STORY: User can customise their profile

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#15]
As a User, I would like to be able to edit my profile details such as my bio, so that I can make sure that I am showing relevant, up-to-date information

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am logged into my account
  When I view my profile
  Then I should be able to edit the details

- Acceptance Criteria 2

  Given that I am logged into my account
  When I click on the button to edit my profile
  Then I should go to the page to edit the details

- Acceptance Criteria 3

  Given that I am logged into my account
  When I view someone elses page
  Then I should not be able to see the edit button

- Acceptance Criteria 4

  Given that I am not logged into my account
  When I type in the address to edit my profile, or anyone elses
  Then I should be redirected to the log in page.

- Acceptance Criteria 5

  Given that I am logged into my account
  When I type in the address to edit someone elses profile
  Then I should be redirected to the home page

**Tasks**

- [x] Develop the option for the user to edit their page
- [x] Develop a page that the user can go to to edit their info
- [x] Add a button to a users profile that only displays on their own page
- [x] Prevent users accessing the edit profile page when not logged in
- [x] Prevent users accessing the edit profile page of other users directly, whether logged in or not.

EPIC: #2

**Comment by Sean-OBrien95** [comment]
Blank
