### ISSUE TITLE
USER STORY: User can change their password

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#17]
As a User, I would like to be able to change my password so that my account stays secure

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am logged in
  When I navigate to the edit profile page
  Then I have the option to change my password

- Acceptance Criteria 2

  Given that I am logged in
  When I change my password
  Then I receive an email confirming my password has been changed

- Acceptance Criteria 3

  Given that I am logged into my account
  When I try to change my password
  Then I am not allowed to create a new password that doesn't meet security needs

- Acceptance Criteria 4

  Given that I am logged in
  When I click the change password link
  Then I am taken to the change password form
  And When I complete the form
  And press enter
  Then My password is changed to the new one
  And I receive confirmation on the screen

**Tasks**

- [ ] Create a form for users to change their password
- [ ] Include a link to the form on the edit profile page to change password
- [ ] Connect the form to the user profile model, so that the new values entered can be captured in the user model
- [ ] Develop form validation to ensure that the password entered meets security needs
- [ ] Create a feedback notification that provide the user with feedback on the successful, or failure of the password change

EPIC: #2

**Comment by Sean-OBrien95** [comment]
Blank

**Comment by Sean-OBrien95** [comment]
Have decided that this is beyond the scope of the project. Will keep as future feature.
