### ISSUE TITLE
USER STORY: Update forgotten password

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#18]
As a User, I would like to be able to reset my forgotten password

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I forgot my password
  When I can't remember my password
  Then there is an option to reset it

- Acceptance Criteria 2

  Given that I click on the link to reset my password
  When I enter my email address that I used to sign up,
  Then I should receive an email with instructions on how to reset my password

- Acceptance Criteria 3

  Given that I received the email to reset my password
  When I follow the instructions
  Then my password I should be able to set a new password of my choosing

**Tasks**

- [ ] Create a link on the login page to take users to a reset password page
- [ ] Develop a form for users to enter their email address in order to reset their password
- [ ] Develop an email containing a link to reset the user password
- [ ] Ensure form for user to enter email address, validates the email address as belonging to current user.
- [ ] Develop time constraint on how long user has to be able to click on the link to reset the password before it expires
- [ ] Functionality requires email address – develop validation of email address in initial user registration process.

EPIC: #2

**Comment by Sean-OBrien95** [comment]
Blank

**Comment by Sean-OBrien95** [comment]
Have decided that this is beyond the scope of the project. Will keep as possible future feature.
