### ISSUE TITLE
USER STORY: Login / Logout functionality

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#19]
As a User, I would like to be able to login or logout of my account

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am a user with an account, who is not logged in
  When I navigate to the sign in page
  And, I enter my credentials correctly and press sign in
  Then I am signed into my account

- Acceptance Criteria 2

  Given that I am a registered user, who is currently logged in
  When I click on the sign out link
  Then I am signed out of my account

- Acceptance Criteria 3

  Given that I am a user, who has signed out of my account
  When I use the browser navigation buttons such as back button
  Then I can not access information which requires me to be signed in

**Tasks**

- [x] Develop the ability for users to sign into their account
- [x] Develop a sign in form to capture the users details
- [x] Develop form validation to ensure the data is correct
- [x] Develop a method to validate the data entered matches a user account
- [x] Develop a link for users to sign out of their account
- [x] Develop a redirect so when a user logs out they are taken to the login home page

EPIC: #3

**Comment by Sean-OBrien95** [comment]
Blank
