### ISSUE TITLE
USER STORY: View posts

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#20]
As a user, I can view the posts on the website

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am a user on the site
  When I navigate to the home page
  Then I am shown the list of posts I can view

- Acceptance Criteria 2

  Given that I am a user on the site
  When I navigate to the home page
  And When I click on a post
  Then I am shown the full contents of the post

**Tasks**

- [x] The home page should list all of the posts
- [x] Develop post cards that display a summary of the post they relate to
- [x] Develop a link from the card to the full post page
- [x] Develop a full post details page that provides the full details

EPIC: #4

**Comment by Sean-OBrien95** [comment]
Blank
