### ISSUE TITLE
USER STORY: Delete posts

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#22]
As an admin user, I can delete a post that I made and remove it from the site entirely

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am an admin user who is logged in, and have created a post
  When I navigate to go to the post I want to delete
  Then I have the option to delete the post

- Acceptance Criteria 2

  Given that I am an admin user who is logged in, has created a post and I am looking at the post that I want to remove
  When I click the delete post button
  Then I receive a confirmation window so that I can confirm the delete or choose to not

- Acceptance Criteria 3

  Given that I am an user who is logged in, have created a post, navigated to that post and clicked the delete button
  When the confirmation window appears and I confirm the deletion
  Then the post is deleted from the site

- Acceptance Criteria 4

  Given that I am a non-admin user
  When I navigate to a post
  Then I do not have the option to delete the post

**Tasks**

- [x] Develop a delete button that appears on the post page when the logged in as an admin user
- [x] Develop a deletion confirmation window that appears when the user clicks the delete button
- [x] Develop the code that deletes the post when the user confirms the deletion, as long as the user is an admin user
- [x] Prevent non admin users from deleting the post by navigating to the direct html address.

EPIC: #4

**Comment by Sean-OBrien95** [comment]
Blank
