### ISSUE TITLE
USER STORY: Create posts

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#23]
As an admin user, I would like to be able to create posts for the community to review

Acceptance Criteria

- Acceptance Criteria 1

  Given that I am an admin user
  When I navigate to the home page
  Then I have the option to create a post

- Acceptance Criteria 2

  Given that I have created a post as an admin user
  When I click the post button
  Then it is available to other users to view

**Tasks**

- [x] Develop a form to enable an admin user to create their post
- [x] Create a model to store the posts
- [x] Connect the form to the post model to create a new post
- [x] Develop the ability to create the record once the post has been uploaded

EPIC: #4

**Comment by Sean-OBrien95** [comment]
Blank
