### ISSUE TITLE
USER STORY: Post searching

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#25]
As a User, I would like to be able to search the post, so that I can find ones that match the topic I'm looking to explore

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am a user of the website
  When I navigate to the site
  Then I can access a search function to access related posts

- Acceptance Criteria 2

  Given that I am a user of the website
  When I search the posts
  Then the search results show relevant posts

**Tasks**

- [x] Develop a search field on the homepage
- [x] Develop search functionality for the search form for post details
- [x] Enable the search query to match either post name, creator name, or key-words

EPIC: #6

**Comment by Sean-OBrien95** [comment]
Blank
