### ISSUE TITLE
USER STORY: Responivness

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#27]
As the owner of the site, I would like my site to be fully responsive, so that users accessing the site from different devices have an enjoyable experience

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that I am a user accessing the site on my smartphone
  When I navigate through the site
  Then all pages should be formatted to my device

- Acceptance Criteria 2

  Given that I am a user accessing the site on my tablet
  When I navigate through the site
  Then all pages should be formatted to my device

- Acceptance Criteria 3

  Given that I am a user accessing the site on my laptop
  When I navigate through the site
  Then all pages should be formatted to my device screen

- Acceptance Criteria 4

  Given that I am a user accessing the site on my desktop computer
  When I navigate the site
  Then all pages should be formatted to suit my screen size

**Tasks**

- [x] Develop all page templates to be fully accessible for mobile devices
- [x] Develop all page templates to be fully responsive for tablet devices
- [x] Develop all page templates to be fully responsive for small monitors
- [x] Develop all page templates to be fully responsive for large monitors
- [x] Develop all user click actions to be accessible via touch

EPIC: #7

**Comment by Sean-OBrien95** [comment]
Blank
