### ISSUE TITLE
USER STORY: Dark mode/Colour preference

### ISSUE THREAD

**Issue by Sean-OBrien95** [Sean-OBrien95/veg-life#28]

**Comment by Sean-OBrien95** [comment]
As the Owner of the site, I would like the site to have a dark colour option, so that users have the ability to view the site in a colour scheme they prefer

**Acceptance Criteria**

- Acceptance Criteria 1

  Given that users visit the site on different devices
  When their device has a preferred-colour-scheme set
  Then the site should be presented in that scheme

- Acceptance Criteria 2

  Given that users visit the site
  When they manually set the colour scheme choice
  Then the site should remember their preference

- Acceptance Criteria 3
  
  Given that users register for the site
  When they log in to the site,
  Then the site should change to their personal colour preference without setting a new preference on that device

**Tasks**

- [ ] Develop the site to include a light and dark colour scheme
- [ ] Develop functionality that checks the user device for a system wide preference
- [ ] Develop functionality that checks the user device for a previously set preference
- [ ] Develop a manual toggle switch that is easily accessible within the main navigation bar to toggle between the light and dark colour schemes.

**Comment by Sean-OBrien95** [comment]
Have decided beyond the scope of this project. Will keep as future feature
